### ISSUE TITLE
Use linter in pipeline

### ISSUE THREAD

**Issue by NatalieClaraPetersen** [itu-devops-groupn/itu-minitwit#28]
Options to explore:
- Use linter to check layers, so that we minimize layers added when deploying
- scan for software licenses

On commit: 
- Check for secrets
- Use codeformatter (readability)

**Comment by NatalieClaraPetersen** [comment]
Use linter to check layers, so that we minimize layers added when deploying?

**Comment by JacobPaerre** [comment]
Super linted added to pipeline on PR's to main branch. It will use Hadolint for Dockerfiles and dotnet format for c#.
